### ISSUE TITLE
Variant that runs w/o UI

### ISSUE THREAD

**Issue by adrientetar** [sansplomb/QuadraticConverter#1]
I understand that `It is not permitted to derive new software from this work in any way.`, however I would like to run this script in batch from CLI. 
Is a freestanding variant of this script feasible?

**Comment by horasio** [comment]
> On 15 avr. 2015, at 10:15, Adrien Tétar notifications@github.com wrote:
> 
> I understand that It is not permitted to derive new software from this work in any way., however I would like to run this script in batch from CLI. 
> Is a freestanding variant of this script feasible?

Adrien,
1. Please use the script for **yourself**  as you wish.
2. Please don’t include it (or code derived from it) in software that you want to sell/distribute.
3. If you want to distribute it, or distribute code derived from it, then please let us know in more detail what you want to do, so we can reach an agreement (which should be very easy to reach I think)

Et mes meilleurs voeux de réussite pour les concours !
— 
Samuel

**Comment by adrientetar** [comment]
Merci, Samuel !

Well, I'm considering this as part of my build process and I intend to release open-source fonts in the future which I'd need to bundle this freestanding script with so people can build the fonts regardless of platform/software (I'm trying to explore various ways to not have to maintain a TTF alongside the PostScript source and stream the updates to the TTF in a graceful way as well). 
So if I understand the intent, it's so that no software uses it as a building block? I would just make a full CLI variant that can be used to build fonts in batch or as part of a build process. I imagine such a script could too be useful for people who work with different editors and different platforms, eventually.
