### ISSUE TITLE
TypeError("'<' not supported between instances of 'Point' and 'Point'")

### ISSUE THREAD

**Issue by luke-snider** [sansplomb/QuadraticConverter#6]
I am getting this: not sure how to solve it?

Unexpected error in QuadraticConverter: (<class 'TypeError'>, TypeError("'<' not supported between instances of 'Point' and 'Point'"), <traceback object at 0x136f8caf0>)

**Comment by horasio** [comment]
Could you give some information about your computer setup? Robofont version, QuadraticConverter version, and more error log if you have more. Thank you!
(It's been years since I last touched QC code, I can't guarantee I'm able to fix this.)

**Comment by horasio** [comment]
Looking at the type error, it might be a class naming clash? Perhaps the ' QC.Point ' class is mistaken for another 'Point'  class ?

**Comment by luke-snider** [comment]
Thanks so much!
I am using Version 3.4b (build 2004251446) and the most recent QC. (old Mac OS: 10.12.6)
I removed some glyphs from the font and it worked. it seem to be a problem with certain glyphs (points?).
You want a test font?

**Comment by horasio** [comment]
yes please, a minimal font. We'll try to test it.

**Comment by luke-snider** [comment]
not sure if uploading here works - just trying:
[typeerror.ufo.zip](https://github.com/BlackFoundry/QuadraticConverter/files/6577435/typeerror.ufo.zip)

**Comment by luke-snider** [comment]
Hi Samuel,
did you figure out what the problem is in the meantime?
Could you reproduce it?
many thanks in advance!

**Comment by BlackFoundry** [comment]
6a00cfca85f1da0004bc6e26962ada524e8c3ade
@luke-snider see if this fix works

**Comment by luke-snider** [comment]
Many thanks! Works now! Great!
